# 史上最全 Vue 前端代码风格指南 [https://yuye.fun/post/d984eb1a.html]
ls:
  .dir: kebab-case
  .js: kebab-case | camelCase
  .jsx: 'PascalCase | regex:^index$'
  .ts: kebab-case | camelCase
  .tsx: 'PascalCase | regex:^index$'
  .d.ts: kebab-case | camelCase
  .mock.ts: camelCase
  .config.js: lowercase
  .css: kebab-case
  .module.css: kebab-case
  .scss: kebab-case
  .module.scss: kebab-case
  .less: kebab-case
  .module.less: kebab-case
  src/pages:
    .tsx: kebabcase

ignore:
  - ./src/pages/_app.tsx
  - ./src/pages/_document.tsx
  - .idea
  - .next
  - .cz-config.js
  - .env-cmdrc.js
  - .eslintrc.js
  - .prettierrc.js
  - .stylelintrc.js
  - .git
  - windi.config.ts
  - dist
  - node_modules
